import { ArrowRight, MessageCircle } from "lucide-react";
import { getImageAlt } from "../lib/imageAlt";

export default function BusinessSiteHero({ template, data, c, bgUrl, coverStyle, products, wa }) {
  if (template === "warm") return <section className="warm-hero"><div className="warm-copy"><small>{c.heroBadge || "RASA YANG BERKESAN"}</small><h1>{c.heroTitle || `Selamat datang di ${data.businessName}`}</h1><p>{c.heroSubtitle || data.description}</p><a data-testid="public-hero-products" href={products.length ? "#menu" : wa}>Lihat pilihan <ArrowRight size={16} /></a></div><img src={bgUrl} alt={getImageAlt({ alt: data.coverImageAlt, context: "Tampilan usaha", businessName: data.businessName })} width="1600" height="900" fetchPriority="high" style={{ objectPosition: coverStyle?.objectPosition, filter: coverStyle?.filter }} /></section>;
  if (template === "bold") return <section className="bold-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(5,10,20,.92), rgba(5,10,20,.35)), url(${bgUrl})`, backgroundPosition: coverStyle?.backgroundPosition, backgroundSize: coverStyle?.backgroundSize }}><div className="bold-headline"><small>{c.heroBadge || data.category}</small><h1>{c.heroTitle || data.businessName}</h1><p>{c.heroSubtitle || data.description}</p><a data-testid="public-hero-products" href={products.length ? "#menu" : wa}><MessageCircle size={17} /> {c.heroCta || "Lihat produk"}</a></div><div className="bold-facts"><span><b>01</b>Kualitas pilihan</span><span><b>02</b>{data.city || "Indonesia"}</span><span><b>03</b>Pesan mudah</span></div></section>;
  if (template === "minimal") return <section className="minimal-hero"><div><small>EST. {data.city || "INDONESIA"}</small><h1>{c.heroTitle || data.businessName}</h1><p>{c.heroSubtitle || data.description}</p><a data-testid="public-hero-products" href={products.length ? "#menu" : wa}>Eksplor koleksi <ArrowRight size={15} /></a></div><figure><img src={bgUrl} alt={getImageAlt({ alt: data.coverImageAlt, context: "Tampilan usaha", businessName: data.businessName })} width="1600" height="900" fetchPriority="high" style={{ objectPosition: coverStyle?.objectPosition, filter: coverStyle?.filter }} /><figcaption>{c.heroBadge || "Pilihan berkualitas untuk keseharian Anda"}</figcaption></figure></section>;
  if (template === "playful") return <section className="playful-hero"><div className="playful-copy"><span>HEY, SELAMAT DATANG! 👋</span><h1>{c.heroTitle || `Hai dari ${data.businessName}!`}</h1><p>{c.heroSubtitle || data.description}</p><a data-testid="public-hero-products" href={products.length ? "#menu" : wa}><MessageCircle size={17} /> {c.heroCta || "Yuk lihat!"}</a></div><div className="playful-picture"><img src={bgUrl} alt={getImageAlt({ alt: data.coverImageAlt, context: "Tampilan usaha", businessName: data.businessName })} width="1600" height="900" fetchPriority="high" style={{ objectPosition: coverStyle?.objectPosition, filter: coverStyle?.filter }} /><i>★</i><b>{data.city || "Pilihan lokal"}</b></div></section>;
  return null;
}
