import { useMemo } from "react";
import { analyzeSeoArticle } from "../lib/seoAnalyzer";
import { SEO_ORIGIN } from "../lib/config";

const labels = { good: "Good", warning: "Warning", issue: "Needs attention", info: "Information", excellent: "Excellent", "needs-improvement": "Needs improvement", "needs-attention": "Needs attention" };
export default function SeoAnalyzerPanel({ article, onFix }) {
  const result = useMemo(() => analyzeSeoArticle(article), [article]);
  return <aside className="seo-analyzer" aria-label="SEO Optimization"><div className="seo-panel-title">SEO OPTIMIZATION</div><div className="seo-score"><div><b>{result.score}</b><span>/100</span></div><p>SEO Score · {labels[result.status]}</p></div><p className="focus-keyword">Focus keyword: <b>{article.focusKeyword || "Add a focus keyword"}</b></p><div className="serp-preview"><small>SEARCH PREVIEW</small><b>{article.seoTitle || article.title || "Judul artikel Situska"}</b><span>{SEO_ORIGIN}/artikel/{article.slug || "slug-artikel"}</span><p>{article.excerpt || "Meta description artikel akan tampil di sini."}</p><small>SEO title: {(article.seoTitle || article.title || "").length} karakter · Meta: {(article.excerpt || "").length} karakter</small></div><div className="seo-summary"><b>Checklist</b><span>✓ {result.summary.good} good · ! {result.summary.warning} warning · × {result.summary.issue} issue · ○ {result.summary.info} info</span></div>{result.checks.map((item) => <details key={item.id} className={`seo-check ${item.status}`}><summary><span>{item.status === "good" ? "✓ Good" : item.status === "warning" ? "! Warning" : item.status === "info" ? "○ Info" : "× Attention"}</span>{item.message}</summary>{item.recommendation && <p><b>{item.priority.toUpperCase()}</b> · {item.recommendation}</p>}{item.id === "seo-title" && !article.seoTitle && <button type="button" onClick={() => onFix("seoTitle", article.title)}>Use Article Title</button>}{item.id === "meta-description" && !article.excerpt && <button type="button" onClick={() => onFix("excerpt", article.title)}>Use Article Title</button>}{item.id === "image" && article.coverImageUrl && !article.coverImageAlt && <button type="button" onClick={() => onFix("coverImageAlt", `Image ${article.title} Situska`)}>Use Article Title</button>}</details>)}</aside>;
}
