import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Plus, Trash2, ExternalLink, FileText, Upload } from "lucide-react";
import { api, errorText, formatDate, resolveMediaUrl, uploadFile } from "../lib/api";
import { Button, FormError, Loading, StatusBadge } from "../lib/shared";
import { SeoHead, originUrl } from "../lib/seo";
import { getImageAlt } from "../lib/imageAlt";
import ArticleEditor from "../components/ArticleEditor";
import { articleToHtml, preparePublicArticleContent, readingMinutes } from "../lib/articleContent";
import SeoAnalyzerPanel from "../components/SeoAnalyzerPanel";
import { getBusinessArticleTemplates, generateBusinessProfileArticle } from "../lib/businessArticleTemplate";
import { getCoverTemplates } from "../lib/imageTemplates";
import { PublicFooter, PublicNav } from "./Landing";
import { publicSiteUrl } from "../lib/config";
import "./Articles.css";

const empty = { title: "", seoTitle: "", slug: "", category: "Website UMKM", focusKeyword: "", excerpt: "", content: "", coverImageUrl: "", coverImageAlt: "", canonicalUrl: "", status: "PUBLISHED" };

function BusinessArticleChrome({ site, children, hosted = false }) {
  const slug = site?.slug || "";
  const homeUrl = hosted ? publicSiteUrl(slug) : `/site/${slug}`;
  const articlesUrl = hosted ? `${publicSiteUrl(slug)}/artikel` : `/site/${slug}/artikel`;
  const logo = resolveMediaUrl(site?.logoUrl || "");
  const primary = site?.themeConfig?.primary || site?.aiGeneratedContent?.primaryColor || "#0077B6";
  const accent = site?.themeConfig?.accent || site?.aiGeneratedContent?.accentColor || "#03045E";
  return <div className="public-site business-article-site" style={{ "--pri": primary, "--acc": accent }}><header className="public-nav"><a className="public-brand" href={homeUrl}>{logo ? <img src={logo} alt={`Logo ${site.businessName}`} /> : <span className="public-brand-initial">{(site?.businessName || "U")[0].toUpperCase()}</span>}<div className="public-brand-title"><b>{site?.businessName}</b><small className="store-status"><span className="status-dot-pulse" /> Buka Hari Ini</small></div></a><nav className="public-nav-links"><a href={`${homeUrl}#tentang`}>Tentang</a><a href={`${homeUrl}#keunggulan`}>Keunggulan</a><a href={`${homeUrl}#menu`}>Produk & Menu</a><a href={`${homeUrl}#testimoni`}>Ulasan</a><a href={`${homeUrl}#faq`}>FAQ</a><a href={`${homeUrl}#lokasi`}>Kontak</a><a href={articlesUrl}>Artikel</a></nav>{site?.whatsapp && <a className="public-nav-cta" href={`https://wa.me/${String(site.whatsapp).replace(/\D/g, "")}`} target="_blank" rel="noreferrer">Chat WhatsApp</a>}</header>{children}<footer className="public-footer-pro"><div className="footer-inner"><div className="footer-brand"><b>{site?.businessName}</b><p>{site?.category || "Usaha"}{site?.city ? ` di ${site.city}` : ""}.</p></div><a className="footer-article-link" href={articlesUrl}>Baca artikel</a><div className="footer-credit"><span>Dibuat dengan Situska</span></div></div></footer></div>;
}

function ArticleCoverPicker({ site, value, onChange, onUpload }) {
  const templates = getCoverTemplates(site.category);
  const businessImages = [site.coverImageUrl, site.logoUrl, ...(site.products || []).flatMap((product) => product.images || [])].filter(Boolean);
  const choose = (url) => onChange({ coverImageUrl: url, coverImageAlt: site.businessName ? `${site.businessName} — ${site.category || "usaha"}` : "" });
  return <section className="article-cover-picker"><div className="article-cover-picker-head"><div><b>Cover artikel</b><small>Pilih dari template, gambar bisnis, foto produk, atau upload gambar sendiri.</small></div><label className="article-cover-upload"><Upload size={15} /> Upload gambar<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => onUpload(e.target.files?.[0])} /></label></div>{value && <div className="article-cover-selected"><img src={resolveMediaUrl(value)} alt="Cover artikel terpilih" /><span>Cover terpilih</span></div>}<div className="article-cover-group"><b>Template {site.category || "usaha"}</b><div className="article-cover-options">{templates.map((item) => <button type="button" key={item.id} className={value === item.url ? "selected" : ""} onClick={() => choose(item.url)}><img src={resolveMediaUrl(item.url)} alt={item.label} /><span>{item.label}</span></button>)}</div></div>{businessImages.length > 0 && <div className="article-cover-group"><b>Gambar dari bisnis dan produk Anda</b><div className="article-cover-options">{businessImages.map((url, index) => <button type="button" key={`${url}-${index}`} className={value === url ? "selected" : ""} onClick={() => choose(url)}><img src={resolveMediaUrl(url)} alt={`Gambar bisnis ${index + 1}`} /><span>{index === 0 ? "Cover bisnis" : `Gambar upload ${index + 1}`}</span></button>)}</div></div>}</section>;
}

export function WebsiteArticles() {
  const { id } = useParams(); const nav = useNavigate();
  const [site, setSite] = useState(null); const [items, setItems] = useState([]); const [form, setForm] = useState(null); const [err, setErr] = useState(""); const [saving, setSaving] = useState(false); const [selectedTemplateId, setSelectedTemplateId] = useState("business-profile");
  const load = () => Promise.all([api.get(`/websites/${id}`), api.get(`/websites/${id}/articles`)]).then(([s, a]) => { setSite(s.data); setItems(a.data); });
  useEffect(() => { load().catch((e) => setErr(errorText(e))); }, [id]);
  if (!site) return <Loading text="Memuat artikel..." />;
  const save = async () => { if (!form.title.trim()) return setErr("Judul artikel wajib diisi."); setSaving(true); setErr(""); try { if (form.id) await api.put(`/articles/${form.id}`, form); else await api.post(`/websites/${id}/articles`, form); setForm(null); await load(); } catch (e) { setErr(errorText(e)); } finally { setSaving(false); } };
  const remove = async (article) => { if (!window.confirm(`Hapus artikel “${article.title}”?`)) return; try { await api.delete(`/articles/${article.id}`); await load(); } catch (e) { setErr(errorText(e)); } };
  const upload = async (file) => { if (!file) return; try { const result = await uploadFile(file); setForm({ ...form, coverImageUrl: result.url }); } catch (e) { setErr(errorText(e)); } };
  const generateProfile = () => {
    setErr("");
    setForm({ ...empty, ...generateBusinessProfileArticle(site, selectedTemplateId) });
  };
  return <div className="dashboard articles-page"><div className="page-head compact"><div><Link className="back-link" to={`/dashboard/websites/${id}`}>← Kembali ke {site.businessName}</Link><div className="eyebrow">ARTIKEL</div><h1>Artikel & promo</h1><p>Tulis konten yang membantu pelanggan menemukan usaha Anda di Google.</p></div><Button onClick={() => setForm({ ...empty })}><Plus size={16} />Buat artikel</Button></div><FormError msg={err} />
    {!form && <section className="article-template-card"><div><div className="eyebrow">TEMPLATE ARTIKEL</div><h2>Pilih template artikel</h2><p>Gunakan data bisnis yang sudah ada untuk menyusun draft awal.</p><select className="article-template-select" value={selectedTemplateId} onChange={(e) => setSelectedTemplateId(e.target.value)}>{getBusinessArticleTemplates(site.category).map((template) => <option key={template.id} value={template.id}>{template.label}</option>)}</select><small>Sumber data: informasi bisnis, produk, keunggulan, FAQ, lokasi, dan kontak dari website ini.</small></div><Button onClick={generateProfile}>Gunakan template</Button></section>}
    {form && <div className="article-page-workspace"><section className="wizard-card article-form"><div className="section-row"><h2>{form.id ? "Edit artikel" : "Artikel baru"}</h2><button className="icon-button" onClick={() => setForm(null)}>Tutup</button></div><div className="form-grid"><label className="full">Judul artikel<input value={form.title} placeholder="Contoh: Cara memilih produk terbaik" onChange={(e) => setForm({ ...form, title: e.target.value, slug: form.slug || e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") })} /></label><label>SEO title<input value={form.seoTitle || ""} placeholder="Judul untuk Google (opsional)" onChange={(e) => setForm({ ...form, seoTitle: e.target.value })} /></label><label>Slug URL<input value={form.slug || ""} placeholder="cara-memilih-produk" onChange={(e) => setForm({ ...form, slug: e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") })} /></label><label className="full">Focus keyword<input value={form.focusKeyword || ""} placeholder="Contoh: produk terbaik" onChange={(e) => setForm({ ...form, focusKeyword: e.target.value })} /></label><label>Kategori<input value={form.category || ""} placeholder="Contoh: Tips belanja" onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label>Publikasi<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="DRAFT">Simpan sebagai draft</option><option value="PUBLISHED">Publikasikan</option></select></label><label className="full">Meta description / ringkasan<textarea maxLength="160" value={form.excerpt} placeholder="Ringkas manfaat artikel dalam 120–160 karakter." onChange={(e) => setForm({ ...form, excerpt: e.target.value })} /><small>{form.excerpt.length}/160 karakter</small></label><label className="full">Isi artikel<small>Gunakan H2 untuk bagian utama dan H3 untuk subbagian.</small><ArticleEditor value={form.content} onChange={(content) => setForm({ ...form, content })} /></label><label className="full">Alt text cover<input value={form.coverImageAlt || ""} placeholder="Jelaskan isi gambar" onChange={(e) => setForm({ ...form, coverImageAlt: e.target.value })} /></label><label className="full">Canonical URL (opsional)<input value={form.canonicalUrl || ""} placeholder="Kosongkan untuk canonical standar" onChange={(e) => setForm({ ...form, canonicalUrl: e.target.value })} /></label></div><ArticleCoverPicker site={site} value={form.coverImageUrl} onChange={(patch) => setForm({ ...form, ...patch })} onUpload={upload} /><div className="wizard-actions"><Button variant="outline" onClick={() => setForm(null)}>Batal</Button><Button onClick={save} disabled={saving}>{saving ? "Menyimpan..." : "Simpan artikel"}</Button></div></section><section className="seo-optimization-sidebar" aria-label="SEO Optimization"><SeoAnalyzerPanel article={form} onFix={(field, value) => setForm({ ...form, [field]: value })} /></section></div>}
    <div className="article-manager-list">{items.map((article) => <article className="article-manager-card" key={article.id}>{article.coverImageUrl && <div className="article-card-cover" style={{ backgroundImage: `url(${resolveMediaUrl(article.coverImageUrl)})` }} />}<div><StatusBadge status={article.status} /><h2>{article.title}</h2><p>{article.excerpt || "Belum ada ringkasan artikel."}</p><small>Diperbarui {formatDate(article.updatedAt)}</small></div><div className="article-card-actions"><button className="text-link" onClick={() => setForm({ ...article })}>Edit</button>{article.status === "PUBLISHED" && site.slug && <a className="text-link" href={`/site/${site.slug}/artikel/${article.slug}`} target="_blank" rel="noreferrer"><ExternalLink size={14} />Lihat</a>}<button className="danger-link" onClick={() => remove(article)}><Trash2 size={14} />Hapus</button></div></article>)}{!items.length && <div className="empty-state"><FileText /><h3>Belum ada artikel</h3><p>Buat artikel pertama untuk promosi dan SEO usaha Anda.</p></div>}</div></div>;
}

export function AdminArticles() { const [items, setItems] = useState(null); useEffect(() => { api.get("/admin/articles").then((r) => setItems(r.data)); }, []); if (!items) return <Loading text="Memuat semua artikel..." />; return <div className="dashboard"><div className="page-head"><div><div className="eyebrow">ARTIKEL</div><h1>Artikel seluruh UMKM</h1><p>Pantau konten yang dibuat oleh semua website.</p></div></div><div className="admin-table"><div className="admin-thead"><span>Artikel</span><span>Website</span><span>Status</span><span>Diperbarui</span><span></span></div>{items.map((a) => <div className="admin-tr" key={a.id}><span><b>{a.title}</b><small>{a.excerpt || "-"}</small></span><span>{a.website?.businessName || "-"}</span><span><StatusBadge status={a.status} /></span><span>{formatDate(a.updatedAt)}</span><span>{a.website?.slug && a.status === "PUBLISHED" && <a className="text-link" target="_blank" rel="noreferrer" href={`/site/${a.website.slug}/artikel/${a.slug}`}>Lihat →</a>}</span></div>)}{!items.length && <div className="empty-inline">Belum ada artikel.</div>}</div></div>; }

export function PublicArticle({ hostedSlug = "" }) { const params = useParams(); const slug = hostedSlug || params.slug; const articleSlug = params.articleSlug || params.slug; const [data, setData] = useState(null); const [site, setSite] = useState(null); const [error, setError] = useState(false); useEffect(() => { Promise.all([api.get(`/public/${slug}/articles/${articleSlug}`), api.get(`/public/${slug}`)]).then(([articleData, siteData]) => { setData(articleData.data); setSite(siteData.data); }).catch(() => setError(true)); }, [slug, articleSlug]); if (error) return <div className="article-public"><h1>Artikel tidak ditemukan.</h1></div>; if (!data || !site) return <Loading text="Membuka artikel..." />; const { website, article } = data; const image = article.coverImageUrl ? (article.coverImageUrl.startsWith("http") ? article.coverImageUrl : `${originUrl()}${article.coverImageUrl}`) : ""; const articleUrl = hostedSlug ? publicSiteUrl(slug, `/${articleSlug}`) : `${originUrl()}/site/${slug}/artikel/${articleSlug}`; const indexUrl = hostedSlug ? `${publicSiteUrl(slug)}/artikel` : `/site/${slug}/artikel`; return <BusinessArticleChrome site={site} hosted={Boolean(hostedSlug)}><main className="article-public"><SeoHead title={`${article.title} | ${website.businessName}`} description={article.excerpt || article.content.slice(0, 155)} image={image} type="article" canonical={articleUrl} schema={{ "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.excerpt, image, datePublished: article.publishedAt, dateModified: article.updatedAt, author: { "@type": "Organization", name: website.businessName }, mainEntityOfPage: articleUrl }} /><a className="back-link" href={indexUrl}>← Semua artikel {website.businessName}</a>{image && <img className="article-public-cover" src={resolveMediaUrl(article.coverImageUrl)} alt={getImageAlt({ alt: article.coverImageAlt, articleTitle: article.title })} />}<div className="eyebrow">ARTIKEL · {website.category}</div><h1>{article.title}</h1><p className="article-lead">{article.excerpt}</p><small>{formatDate(article.publishedAt || article.updatedAt)}</small><div className="article-body" dangerouslySetInnerHTML={{ __html: articleToHtml(article.content) }} /></main></BusinessArticleChrome>; }

export function PublicWebsiteArticles({ hostedSlug = "" }) {
  const { slug: routeSlug } = useParams(); const slug = hostedSlug || routeSlug;
  const [items, setItems] = useState(null);
  const [site, setSite] = useState(null);
  useEffect(() => {
    Promise.all([api.get(`/public/${slug}`), api.get(`/public/${slug}/articles`)])
      .then(([website, articles]) => { setSite(website.data); setItems(articles.data); })
      .catch(() => setItems([]));
  }, [slug]);
  if (!items) return <Loading text="Memuat artikel..." />;
  const name = site?.businessName || "Website";
  const indexUrl = hostedSlug ? `${publicSiteUrl(slug)}/artikel` : `/site/${slug}/artikel`; const homeUrl = hostedSlug ? publicSiteUrl(slug) : `/site/${slug}`;
  return <BusinessArticleChrome site={site} hosted={Boolean(hostedSlug)}><main className="article-public article-index business-article-index">
    <SeoHead title={`Artikel ${name}`} description={`Artikel dan informasi terbaru dari ${name}.`} canonical={indexUrl} />
    <a className="back-link" href={homeUrl}>← Kembali ke {name}</a>
    <div className="eyebrow">ARTIKEL {name.toUpperCase()}</div><h1>Artikel & informasi terbaru</h1>
    <p className="article-lead">Temukan informasi, produk, dan cerita terbaru dari {name}.</p>
    <div className="article-index-grid">{items.map((article) => <article key={article.id}><a href={hostedSlug ? publicSiteUrl(slug, `/${article.slug}`) : `/site/${slug}/artikel/${article.slug}`}>{article.coverImageUrl && <img src={resolveMediaUrl(article.coverImageUrl)} alt={getImageAlt({ alt: article.coverImageAlt, articleTitle: article.title })} loading="lazy" />}<small className="article-category">{article.category || "Artikel"}</small><h2>{article.title}</h2><p>{article.excerpt}</p><small>{formatDate(article.publishedAt || article.updatedAt)}</small></a></article>)}</div>
    {!items.length && <div className="empty-state"><FileText /><h3>Belum ada artikel</h3><p>Artikel terbaru dari {name} akan tampil di halaman ini.</p></div>}
  </main></BusinessArticleChrome>;
}

export function AdminBuildzaArticles() {
  const [items, setItems] = useState(null); const [form, setForm] = useState(null); const [err, setErr] = useState(""); const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState("ALL"); const [categoryFilter, setCategoryFilter] = useState("ALL"); const [page, setPage] = useState(1); const [preview, setPreview] = useState(false);
  const load = () => api.get("/admin/buildza-articles").then((r) => setItems(r.data));
  useEffect(() => { load().catch((e) => setErr(errorText(e))); }, []);
  if (!items) return <Loading text="Memuat artikel Situska..." />;
  const save = async () => { if (!form.title.trim()) return setErr("Judul artikel wajib diisi."); try { if (form.id) await api.put(`/admin/buildza-articles/${form.id}`, form); else await api.post("/admin/buildza-articles", form); setForm(null); await load(); } catch (e) { setErr(errorText(e)); } };
  const upload = async (file) => { if (!file) return; try { const r = await uploadFile(file); setForm({ ...form, coverImageUrl: r.url }); } catch (e) { setErr(errorText(e)); } };
  const remove = async (item) => { if (!window.confirm(`Hapus artikel “${item.title}”?`)) return; try { await api.delete(`/admin/buildza-articles/${item.id}`); await load(); } catch (e) { setErr(errorText(e)); } };
  const categories = [...new Set(items.map((item) => item.category || "Website UMKM"))]; const filtered = items.filter((item) => (!query || `${item.title} ${item.slug}`.toLowerCase().includes(query.toLowerCase())) && (statusFilter === "ALL" || item.status === statusFilter) && (categoryFilter === "ALL" || (item.category || "Website UMKM") === categoryFilter)); const totalPages = Math.max(1, Math.ceil(filtered.length / 10)); const paged = filtered.slice((Math.min(page, totalPages) - 1) * 10, Math.min(page, totalPages) * 10);
  return <div className="dashboard articles-page"><div className="page-head"><div><div className="eyebrow">SEO SITUSKA</div><h1>Artikel Situska</h1><p>Konten resmi Situska untuk mendatangkan calon pengguna dari Google.</p></div><Button onClick={() => setForm({ ...empty })}><Plus size={16} />Tulis artikel</Button></div><FormError msg={err} />
    {form && <div className="article-page-workspace"><section className="wizard-card article-form"><div className="section-row"><h2>{form.id ? "Edit artikel Situska" : "Artikel Situska baru"}</h2><button className="icon-button" onClick={() => setForm(null)}>Tutup</button></div><div className="form-grid">
      <label className="full">Judul artikel<input value={form.title} placeholder="Cara membuat website gratis untuk UMKM" onChange={(e) => setForm({ ...form, title: e.target.value, slug: form.slug || e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") })} /></label>
      <label>SEO title<input value={form.seoTitle || ""} placeholder="Opsional: judul untuk Google" onChange={(e) => setForm({ ...form, seoTitle: e.target.value })} /></label><label>Slug URL<input value={form.slug || ""} placeholder="cara-membuat-website-umkm" onChange={(e) => setForm({ ...form, slug: e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") })} /></label><label className="full">Focus keyword<input value={form.focusKeyword || ""} placeholder="Contoh: website UMKM" onChange={(e) => setForm({ ...form, focusKeyword: e.target.value })} /><small>Gunakan satu frasa utama yang benar-benar sesuai dengan topik artikel.</small></label>
      <label>Kategori<select value={form.category || "Website UMKM"} onChange={(e) => setForm({ ...form, category: e.target.value })}>{["Website UMKM", "SEO", "Marketing", "WhatsApp", "Digitalisasi UMKM", "Jenis Usaha"].map((category) => <option key={category}>{category}</option>)}</select></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="DRAFT">Draft</option><option value="PUBLISHED">Publish</option></select></label>
      <label className="full">Meta description / ringkasan<textarea value={form.excerpt} maxLength="160" placeholder="Ringkas manfaat artikel dalam 120–160 karakter." onChange={(e) => setForm({ ...form, excerpt: e.target.value })} /><small>{form.excerpt.length}/160 karakter</small></label>
      <label className="full">Isi artikel<small>Gunakan H2 untuk bagian utama dan H3 untuk subbagian. Konten lama tetap aman sebagai paragraf.</small><ArticleEditor value={form.content} onChange={(content) => setForm({ ...form, content })} /></label>
      <label>URL cover image<input value={form.coverImageUrl} onChange={(e) => setForm({ ...form, coverImageUrl: e.target.value })} /></label><label>Alt text cover<input value={form.coverImageAlt || ""} placeholder="Jelaskan isi gambar" onChange={(e) => setForm({ ...form, coverImageAlt: e.target.value })} /></label><label className="full">Canonical URL (opsional)<input value={form.canonicalUrl || ""} placeholder="Kosongkan untuk canonical artikel Situska" onChange={(e) => setForm({ ...form, canonicalUrl: e.target.value })} /></label>
    </div><label className="template-upload">Upload cover image<input type="file" accept="image/*" onChange={(e) => upload(e.target.files?.[0])} /></label><div className="wizard-actions"><Button variant="outline" onClick={() => setForm(null)}>Batal</Button><Button variant="outline" onClick={() => setPreview(!preview)}>Preview artikel</Button><Button onClick={save}>Simpan artikel</Button></div>{preview && <article className="article-preview"><div className="eyebrow">{form.category}</div><h1>{form.title || "Judul artikel"}</h1><p className="article-lead">{form.excerpt}</p>{form.coverImageUrl && <img src={resolveMediaUrl(form.coverImageUrl)} alt={getImageAlt({ alt: form.coverImageAlt, articleTitle: form.title })} />}<div className="article-body" dangerouslySetInnerHTML={{ __html: articleToHtml(form.content) }} /><section className="article-funnel"><h2>Sudah siap punya website untuk usaha Anda?</h2><Link className="btn btn-primary" to="/register">Buat Website Gratis</Link></section></article>}</section><section className="seo-optimization-sidebar" aria-label="SEO Optimization"><SeoAnalyzerPanel article={form} onFix={(field, value) => setForm({ ...form, [field]: value })} /></section></div>}
    <div className="article-admin-filters"><input aria-label="Cari artikel" value={query} placeholder="Cari judul atau slug" onChange={(e) => { setQuery(e.target.value); setPage(1); }} /><select value={statusFilter} onChange={(e) => { setStatusFilter(e.target.value); setPage(1); }}><option value="ALL">Semua status</option><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select><select value={categoryFilter} onChange={(e) => { setCategoryFilter(e.target.value); setPage(1); }}><option value="ALL">Semua kategori</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></div>
    <div className="article-admin-list">{paged.map((item) => <article className="article-admin-row" key={item.id}><div><StatusBadge status={item.status} /><b>{item.title}</b><small>/{item.slug} · {item.category || "Website UMKM"} · Diperbarui {formatDate(item.updatedAt)}</small></div><div className="article-card-actions"><button className="text-link" onClick={() => setForm({ ...empty, ...item })}>Edit</button>{item.status === "PUBLISHED" && <a className="text-link" href={`/${item.slug}`} target="_blank" rel="noreferrer">Lihat</a>}<button className="danger-link" onClick={() => remove(item)}><Trash2 size={14} />Hapus</button></div></article>)}{!filtered.length && <div className="empty-state"><FileText /><h3>Artikel tidak ditemukan</h3><p>Ubah kata pencarian atau filter Anda.</p></div>}</div>{totalPages > 1 && <nav className="article-pagination" aria-label="Pagination artikel"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Sebelumnya</button><span>Halaman {Math.min(page, totalPages)} dari {totalPages}</span><button disabled={page === totalPages} onClick={() => setPage(page + 1)}>Berikutnya</button></nav>}</div>;
}

export function PublicBuildzaArticle() {
  const { articleSlug } = useParams(); const [article, setArticle] = useState(null); const [related, setRelated] = useState([]); const [error, setError] = useState(false);
  useEffect(() => { api.get(`/content/buildza-articles/${articleSlug}`).then((r) => { if (r.data.redirectTo) { window.location.replace(r.data.redirectTo); return null; } const current = r.data; setArticle(current); return api.get("/content/buildza-articles").then((all) => ({ current, all: all.data })); }).then((payload) => { if (!payload) return; const { current, all } = payload; const terms = (current.focusKeyword || current.title).toLowerCase().split(/\s+/).filter((term) => term.length > 3); setRelated(all.filter((item) => item.slug !== articleSlug).sort((a, b) => { const score = (item) => (item.category === current.category ? 4 : 0) + terms.filter((term) => `${item.title} ${item.focusKeyword || ""}`.toLowerCase().includes(term)).length; return score(b) - score(a) || String(b.publishedAt || "").localeCompare(String(a.publishedAt || "")); }).slice(0, 3)); }).catch(() => setError(true)); }, [articleSlug]);
  const renderedContent = useMemo(() => preparePublicArticleContent(article?.content || ""), [article?.content]);
  if (error) return <div className="article-public"><h1>Artikel tidak ditemukan.</h1></div>; if (!article) return <Loading text="Membuka artikel..." />;
  const image = article.coverImageUrl ? (article.coverImageUrl.startsWith("http") ? article.coverImageUrl : `${originUrl()}${article.coverImageUrl}`) : ""; const canonical = article.canonicalUrl || `/${articleSlug}`; const minutes = readingMinutes(article.content);
  const schema = [{ "@context": "https://schema.org", "@type": "Article", headline: article.seoTitle || article.title, description: article.excerpt, image, datePublished: article.publishedAt, dateModified: article.updatedAt, author: { "@type": "Organization", name: "Situska" }, publisher: { "@type": "Organization", name: "Situska" }, mainEntityOfPage: `${originUrl()}${canonical}` }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Beranda", item: originUrl() }, { "@type": "ListItem", position: 2, name: "Artikel", item: `${originUrl()}/artikel` }, { "@type": "ListItem", position: 3, name: article.title, item: `${originUrl()}${canonical}` }] }];
  return <div className="landing article-page"><SeoHead title={`${article.seoTitle || article.title} | Situska`} description={article.excerpt || article.content.replace(/<[^>]*>/g, " ").slice(0, 155)} image={image} type="article" canonical={canonical} schema={schema} /><PublicNav /><main className="article-public"><nav className="article-breadcrumb" aria-label="Breadcrumb"><Link to="/artikel">Artikel</Link><span>›</span><span>{article.title}</span></nav><div className="eyebrow">{article.category || "ARTIKEL SITUSKA"}</div><h1>{article.title}</h1><p className="article-lead">{article.excerpt}</p><small>{formatDate(article.publishedAt || article.updatedAt)} · {minutes} menit baca</small>{image && <img className="article-public-cover" src={resolveMediaUrl(article.coverImageUrl)} alt={getImageAlt({ alt: article.coverImageAlt, articleTitle: article.title })} width="1200" height="630" />}{renderedContent.headings.length > 0 && <nav className="article-toc" aria-label="Daftar isi"><b>Daftar isi</b><ol>{renderedContent.headings.map((heading) => <li className={`level-${heading.level}`} key={heading.id}><a href={`#${heading.id}`}>{heading.label}</a></li>)}</ol></nav>}<article className="article-body" dangerouslySetInnerHTML={{ __html: renderedContent.html }} /><section className="article-funnel"><h2>Sudah siap punya website untuk usaha Anda?</h2><p>Buat website profesional, tampilkan produk, dan terima pelanggan tanpa perlu coding.</p><Link className="btn btn-primary" to="/register">Buat Website Gratis</Link></section>{related.length > 0 && <section className="related-articles"><h2>Artikel terkait</h2><div className="article-index-grid related-article-grid">{related.map((item) => <article key={item.id}><Link to={`/${item.slug}`}>{item.coverImageUrl && <img src={resolveMediaUrl(item.coverImageUrl)} alt={getImageAlt({ alt: item.coverImageAlt, articleTitle: item.title })} loading="lazy" width="600" height="340" />}<small className="article-category">{item.category || "Artikel Situska"}</small><h3>{item.title}</h3><p>{item.excerpt}</p><small>{formatDate(item.publishedAt || item.updatedAt)}</small></Link></article>)}</div></section>}</main><PublicFooter /></div>;
}

export function PublicBuildzaArticles() { const [items, setItems] = useState(null); useEffect(() => { api.get("/content/buildza-articles").then((r) => setItems(r.data)).catch(() => setItems([])); }, []); if (!items) return <Loading text="Memuat artikel Situska..." />; return <div className="landing article-page"><SeoHead title="Artikel Situska | Panduan Website Usaha" description="Panduan membuat website usaha, website UMKM, katalog produk, dan pemasaran digital untuk bisnis Indonesia." canonical="/artikel" schema={{ "@context": "https://schema.org", "@type": "CollectionPage", name: "Artikel Situska" }} /><PublicNav /><main className="article-public article-index"><div className="eyebrow">PANDUAN SITUSKA</div><h1>Panduan website usaha</h1><p className="article-lead">Tips praktis untuk membuat website usaha, memasarkan produk, dan bertumbuh online.</p><div className="article-index-grid">{items.map((item) => <article key={item.id}><Link to={`/${item.slug}`}>{item.coverImageUrl && <img src={resolveMediaUrl(item.coverImageUrl)} alt={getImageAlt({ alt: item.coverImageAlt, articleTitle: item.title })} loading="lazy" width="600" height="340" />}<small className="article-category">{item.category || "Website UMKM"} · {readingMinutes(item.content)} menit baca</small><h2>{item.title}</h2><p>{item.excerpt}</p><small>{formatDate(item.publishedAt || item.updatedAt)}</small></Link></article>)}{!items.length && <p>Artikel Situska akan segera hadir.</p>}</div></main><PublicFooter /></div>; }

export function PublicArticleCategory() {
  const { categorySlug } = useParams(); const [items, setItems] = useState(null); const category = categorySlug.split("-").map((word) => word[0].toUpperCase() + word.slice(1)).join(" ");
  useEffect(() => { api.get("/content/buildza-articles").then((r) => setItems(r.data.filter((item) => (item.category || "Website UMKM").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") === categorySlug))).catch(() => setItems([])); }, [categorySlug]);
  if (!items) return <Loading text="Memuat artikel..." />; if (!items.length) return <div className="landing"><PublicNav /><main className="article-public"><h1>Kategori tidak ditemukan</h1><p>Kategori artikel ini belum memiliki konten yang dipublikasikan.</p><Link to="/artikel">Kembali ke artikel</Link></main><PublicFooter /></div>;
  const title = `Artikel ${category} | Situska`; return <div className="landing article-page"><SeoHead title={title} description={`Panduan ${category} untuk membantu usaha Indonesia bertumbuh secara online.`} canonical={`/artikel/kategori/${categorySlug}`} schema={{ "@context": "https://schema.org", "@type": "CollectionPage", name: title }} /><PublicNav /><main className="article-public article-index"><nav className="article-breadcrumb" aria-label="Breadcrumb"><Link to="/">Beranda</Link><span>›</span><Link to="/artikel">Artikel</Link><span>›</span><span>{category}</span></nav><div className="eyebrow">KATEGORI ARTIKEL</div><h1>{category}</h1><p className="article-lead">Artikel Situska seputar {category} untuk UMKM Indonesia.</p><div className="article-index-grid">{items.map((item) => <article key={item.id}><Link to={`/artikel/${item.slug}`}>{item.coverImageUrl && <img src={resolveMediaUrl(item.coverImageUrl)} alt={getImageAlt({ alt: item.coverImageAlt, articleTitle: item.title })} loading="lazy" width="600" height="340" />}<h2>{item.title}</h2><p>{item.excerpt}</p></Link></article>)}</div></main><PublicFooter /></div>;
}
