import { Link } from "react-router-dom";
import { ArrowRight, Check } from "lucide-react";
import { SeoHead } from "../lib/seo";

const pages = {
  "website-toko-online": { title: "Website Toko Online untuk Usaha | Situska", h1: "Buat Website Toko Online dengan Mudah", intro: "Tampilkan produk, harga, foto, dan link pemesanan WhatsApp dalam website toko online yang rapi.", benefits: ["Katalog produk yang jelas", "Pelanggan dapat langsung pesan via WhatsApp", "Mudah diperbarui saat ada produk baru"], example: "Nusa Craft", faq: ["Apakah bisa menambahkan banyak produk?", "Apakah pelanggan dapat memesan melalui WhatsApp?"] },
  "website-cafe": { title: "Website Cafe Profesional | Situska", h1: "Buat Website Cafe Tanpa Coding", intro: "Perkenalkan menu, suasana, lokasi, dan nomor WhatsApp cafe Anda melalui website yang mudah ditemukan pelanggan.", benefits: ["Menu dan harga tersusun rapi", "Lokasi cafe mudah dibagikan", "Promo dan artikel dapat diperbarui"], example: "Kopi Senja", faq: ["Bisakah saya menampilkan menu cafe?", "Apakah website cafe dapat dibuka dari ponsel?"] },
  "website-restoran": { title: "Website Restoran Profesional | Situska", h1: "Buat Website Restoran dengan Mudah", intro: "Website restoran untuk menampilkan menu, informasi lokasi, jam buka, dan cara pemesanan pelanggan.", benefits: ["Katalog menu yang enak dilihat", "Informasi restoran mudah dicari", "Pesan makanan melalui WhatsApp"], example: "Warung Sundari", faq: ["Bisakah restoran menampilkan menu dan harga?", "Apakah saya bisa mengubah jam buka?"] },
  "website-bengkel": { title: "Website Bengkel Profesional | Situska", h1: "Buat Website Bengkel Tanpa Coding", intro: "Buat website bengkel untuk menjelaskan layanan, lokasi, jam operasional, dan nomor yang bisa dihubungi pelanggan.", benefits: ["Layanan bengkel terlihat lebih tepercaya", "Pelanggan cepat menemukan lokasi", "Konsultasi langsung lewat WhatsApp"], example: "Bengkel Anda", faq: ["Apakah bisa menampilkan layanan bengkel?", "Apakah saya perlu bisa coding?"] },
  "website-barbershop": { title: "Website Barbershop Profesional | Situska", h1: "Buat Website Barbershop dengan Mudah", intro: "Tampilkan layanan grooming, daftar harga, lokasi, dan kontak barbershop Anda dengan lebih profesional.", benefits: ["Daftar layanan dan harga yang jelas", "Tautan WhatsApp untuk booking", "Tampilan optimal di perangkat mobile"], example: "Barber Co", faq: ["Bisakah pelanggan booking lewat WhatsApp?", "Apakah website dapat menampilkan lokasi barbershop?"] },
  "website-bakery": { title: "Website Bakery Profesional | Situska", h1: "Buat Website Bakery Tanpa Coding", intro: "Buat website bakery untuk memajang roti, kue, paket hampers, serta informasi pemesanan dengan mudah.", benefits: ["Foto produk bakery tampil menarik", "Produk dan paket mudah diperbarui", "Pemesanan mengarah ke WhatsApp"], example: "Rumah Roti", faq: ["Bisakah saya memasang foto roti dan kue?", "Apakah bisa menambah promo hampers?"] },
  "website-jasa": { title: "Website Jasa Profesional | Situska", h1: "Buat Website Jasa Tanpa Coding", intro: "Jelaskan layanan, portofolio, area layanan, dan cara konsultasi melalui website jasa yang profesional.", benefits: ["Penawaran jasa lebih mudah dipahami", "Kontak pelanggan lebih cepat", "Artikel membantu membangun kepercayaan"], example: "Usaha Jasa Anda", faq: ["Apakah website jasa bisa memuat portofolio?", "Apakah saya bisa mengubah isi website sendiri?"] },
};

export function SeoLandingPage({ pageKey }) {
  const p = pages[pageKey];
  if (!p) return null;
  const canonical = `/${pageKey}`;
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: p.faq.map((q) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: "Situska membantu membuat website usaha tanpa coding, dengan informasi dan fitur yang dapat Anda kelola sendiri." } })) };
  return <main className="seo-landing"><SeoHead title={p.title} description={p.intro} canonical={canonical} image="/assets/showcase/kopi-senja-cover.png" schema={[{ "@context": "https://schema.org", "@type": "WebPage", name: p.h1, description: p.intro }, faqSchema]} /><section className="seo-hero"><div className="eyebrow">SITUSKA UNTUK USAHA INDONESIA</div><h1>{p.h1}</h1><p>{p.intro}</p><Link className="btn btn-primary" to="/register">Buat Website Gratis <ArrowRight size={16} /></Link></section><section className="seo-section"><h2>Semua yang dibutuhkan {pageKey.replace("website-", "website ")}</h2><div className="seo-benefits">{p.benefits.map((benefit) => <div key={benefit}><Check size={18} />{benefit}</div>)}</div></section><section className="seo-section seo-example"><div><div className="eyebrow">CONTOH WEBSITE</div><h2>{p.example}</h2><p>Contoh website usaha dengan informasi bisnis, katalog produk, dan kontak yang mudah dijangkau pelanggan.</p><Link className="text-link" to="/site/demo-kopi-senja">Lihat contoh website usaha <ArrowRight size={15} /></Link></div><div className="seo-card">01<br /><b>Isi informasi usaha</b><br />02<br /><b>Tambahkan produk</b><br />03<br /><b>Publish website</b></div></section><section className="seo-section"><h2>Pertanyaan umum</h2>{p.faq.map((question) => <details key={question}><summary>{question}</summary><p>Ya. Situska dirancang agar pemilik usaha dapat membuat dan mengelola website tanpa coding.</p></details>)}</section><section className="seo-cta"><h2>Website usaha siap dalam beberapa klik.</h2><Link className="btn btn-primary" to="/register">Buat Website Gratis <ArrowRight size={16} /></Link><p><Link to="/artikel">Artikel Situska</Link></p></section></main>;
}

export const SEO_PAGE_KEYS = Object.keys(pages);
