import { articleToHtml } from "./articleContent";

const strip = (value = "") => String(value).replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
const words = (value) => strip(value).split(/\s+/).filter(Boolean);
const has = (value, keyword) => keyword && String(value || "").toLowerCase().includes(keyword.toLowerCase());
const check = (id, status, message, recommendation, points, priority = "low") => ({ id, status, message, recommendation, points, priority });

export function analyzeSeoArticle({ title = "", seoTitle = "", excerpt = "", slug = "", focusKeyword = "", content = "", coverImageUrl = "", coverImageAlt = "" } = {}) {
  const html = articleToHtml(content); const text = strip(html); const count = words(text).length; const keyword = focusKeyword.trim(); const titleForSeo = seoTitle.trim() || title.trim();
  const occurrences = keyword ? (text.toLowerCase().match(new RegExp(keyword.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "g")) || []).length : 0;
  const frequency = count ? +(occurrences / count * 100).toFixed(1) : 0;
  const intro = text.slice(0, 500); const h2Count = (html.match(/<h2\b/gi) || []).length; const h3Count = (html.match(/<h3\b/gi) || []).length;
  const links = [...html.matchAll(/<a[^>]+href=["']([^"']+)/gi)].map((m) => m[1]); const internalLinks = links.filter((url) => /^\//.test(url) || /situska\.com/i.test(url)).length; const externalLinks = links.length - internalLinks;
  const paragraphs = [...html.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/gi)].map((m) => strip(m[1])); const longParagraphs = paragraphs.filter((p) => words(p).length > 110).length; const longSentences = (text.match(/[^.!?]+[.!?]+/g) || []).filter((sentence) => words(sentence).length > 28).length;
  const checks = [];
  checks.push(!titleForSeo ? check("seo-title", "issue", "SEO title belum tersedia.", "Tambahkan SEO title yang menjelaskan manfaat artikel.", 0) : titleForSeo.length > 65 ? check("seo-title", "warning", "SEO title cukup panjang.", "Pertimbangkan mempersingkat agar lebih mudah ditampilkan pada hasil pencarian.", 6) : titleForSeo.length < 30 ? check("seo-title", "warning", "SEO title cukup pendek.", "Tambahkan konteks manfaat atau topik utama artikel.", 7) : check("seo-title", "good", "SEO title memiliki panjang yang baik.", "", 10));
  checks.push(!excerpt.trim() ? check("meta-description", "issue", "Meta description belum tersedia.", "Tulis ringkasan 120–160 karakter yang membantu pembaca memahami artikel.", 0) : excerpt.length > 165 ? check("meta-description", "warning", "Meta description cukup panjang.", "Pertimbangkan mempersingkat agar ringkas dan mudah dipindai.", 6) : excerpt.length < 110 ? check("meta-description", "warning", "Meta description cukup pendek.", "Tambahkan ringkasan manfaat artikel secara natural.", 7) : check("meta-description", "good", "Meta description memiliki panjang yang baik.", "", 10));
  checks.push(!slug ? check("slug", "issue", "Slug URL belum tersedia.", "Buat URL singkat dan mudah dibaca.", 0) : !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug) || slug.length > 75 ? check("slug", "warning", "Slug URL perlu dirapikan.", "Gunakan lowercase, hyphen, dan URL yang singkat.", 6) : check("slug", "good", "URL slug bersih dan mudah dibaca.", "", 8));
  checks.push(!title.trim() ? check("h1", "issue", "H1 belum tersedia.", "Tambahkan judul artikel; halaman publik memakai judul ini sebagai satu H1.", 0, "high") : check("h1", "good", "H1 tersedia dari judul artikel.", "", 6, "info"));
  checks.push(count < 180 ? check("content-length", "warning", `Artikel masih singkat (${count} kata).`, "Tambahkan penjelasan yang benar-benar membantu pembaca bila topik membutuhkan detail.", 4) : check("content-length", "good", `Panjang konten cukup (${count} kata).`, "", 10));
  checks.push(h2Count === 0 ? check("headings", "warning", "Belum ada H2 pada artikel.", "Gunakan H2 untuk membagi pembahasan menjadi bagian yang mudah dipindai.", 3) : check("headings", "good", `Struktur konten memiliki ${h2Count} H2${h3Count ? ` dan ${h3Count} H3` : ""}.`, "", 8));
  checks.push(!coverImageUrl ? check("image", "warning", "Cover image belum tersedia.", "Tambahkan cover yang relevan untuk meningkatkan konteks visual artikel.", 2) : !coverImageAlt.trim() ? check("image", "warning", "Cover menggunakan alt text otomatis.", "Tambahkan deskripsi gambar manual agar lebih informatif.", 5) : check("image", "good", "Cover image memiliki alt text manual.", "", 8));
  checks.push(internalLinks ? check("internal-links", "good", `Artikel memiliki ${internalLinks} internal link.`, "", 7) : check("internal-links", "warning", "Belum ada internal link.", "Tambahkan link ke artikel atau halaman Situska yang relevan.", 2));
  checks.push(check("external-links", "info", externalLinks ? `Terdeteksi ${externalLinks} external link.` : "Tidak ada external link.", "External link hanya diperlukan bila ada sumber relevan untuk pembaca.", 0, "info"));
  checks.push(longParagraphs || longSentences > 2 ? check("readability", "warning", "Beberapa bagian cukup padat untuk dipindai.", "Pecah paragraf panjang atau gunakan subheading dan list bila sesuai.", 4) : check("readability", "good", "Konten cukup mudah dipindai.", "", 7));
  if (keyword) {
    checks.push(check("keyword-title", has(titleForSeo, keyword) ? "good" : "issue", has(titleForSeo, keyword) ? "Focus keyword ditemukan di SEO title." : "Focus keyword belum ditemukan di SEO title.", "Gunakan keyword bila tetap natural.", has(titleForSeo, keyword) ? 6 : 0));
    checks.push(check("keyword-meta", has(excerpt, keyword) ? "good" : "warning", has(excerpt, keyword) ? "Focus keyword ditemukan di meta description." : "Focus keyword belum ditemukan di meta description.", "Pertimbangkan menambahkannya bila cocok dengan ringkasan.", has(excerpt, keyword) ? 5 : 2));
    checks.push(check("keyword-placement", has(slug, keyword.replace(/\s+/g, "-")) && has(title, keyword) && has(intro, keyword) && occurrences ? "good" : "warning", `Penempatan keyword: ${[has(titleForSeo, keyword) && "SEO title", has(slug, keyword.replace(/\s+/g, "-")) && "URL", has(title, keyword) && "H1", has(intro, keyword) && "introduction", occurrences && "body", has(coverImageAlt, keyword) && "image alt"].filter(Boolean).join(", ") || "belum ditemukan"}.`, "Gunakan keyword secara natural, tanpa mengulang secara berlebihan.", has(title, keyword) && has(intro, keyword) && occurrences ? 8 : 3));
    checks.push(check("keyword-frequency", frequency > 3 ? "warning" : occurrences ? "good" : "warning", `Focus keyword muncul ${occurrences} kali (~${frequency}%).`, frequency > 3 ? "Keyword cukup sering; pastikan tulisan tetap natural." : "Tidak ada kepadatan keyword wajib—utamakan keterbacaan.", occurrences ? 5 : 1));
  }
  const total = checks.reduce((sum, item) => sum + item.points, 0); const possible = keyword ? 92 : 68; const score = Math.round(Math.min(100, total / possible * 100));
  return { score, status: score >= 90 ? "excellent" : score >= 75 ? "good" : score >= 50 ? "needs-improvement" : "needs-attention", checks, wordCount: count, keywordOccurrences: occurrences, keywordFrequency: frequency, internalLinks, externalLinks, summary: { good: checks.filter((item) => item.status === "good").length, warning: checks.filter((item) => item.status === "warning").length, issue: checks.filter((item) => item.status === "issue").length, info: checks.filter((item) => item.status === "info").length } };
}
