const logo = (name, color) => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96"><rect width="96" height="96" rx="26" fill="${color}"/><path d="M25 55h46M31 45h34M37 35h22" stroke="white" stroke-width="6" stroke-linecap="round"/><text x="48" y="78" text-anchor="middle" fill="white" font-family="Arial,sans-serif" font-size="15" font-weight="700">${name.split(" ").map((word) => word[0]).join("").slice(0, 2)}</text></svg>`)}`;

// Semua media demo berada di project agar stabil dan selalu sesuai produk.
const assetSlug = (value) => value.toLowerCase().replace(/\+/g, " ").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const productPhoto = (siteSlug, name) => `/assets/showcase/${siteSlug.replace("demo-", "")}-${assetSlug(name)}.png`;
const coverPhoto = (siteSlug) => `/assets/showcase/${siteSlug.replace("demo-", "")}-cover.png`;

const profiles = {
  "demo-kopi-senja": { about: "Kopi Senja lahir dari kebiasaan menikmati kopi pelan-pelan. Kami meracik minuman per pesanan dengan biji lokal pilihan dan menyajikannya paling nikmat untuk dinikmati di kedai atau diantar di area sekitar.", highlights: [["Diracik saat dipesan", "Setiap gelas dibuat setelah pesanan masuk agar rasa dan suhu tetap terjaga.", "Coffee"], ["Biji kopi lokal", "Kami memilih biji yang cocok untuk espresso maupun susu.", "Bean"], ["Antar dekat, tetap segar", "Minuman tersedia untuk pick-up dan pengantaran lokal, bukan pengiriman antarkota.", "MapPin"]], faq: [["Apakah minuman bisa dikirim ke luar kota?", "Belum. Minuman kami dibuat segar dan hanya tersedia untuk pick-up atau pengantaran di area sekitar kedai."], ["Bisa atur tingkat gula atau es?", "Bisa. Sampaikan preferensi gula dan es melalui WhatsApp saat memesan."], ["Apakah ada pilihan non-kopi?", "Ada, seperti Matcha Latte dan pilihan pastry untuk teman minum."], ["Kapan pesanan dibuat?", "Pesanan diracik setelah dikonfirmasi agar tetap segar."], ["Bisa pesan untuk rapat kecil?", "Bisa, hubungi kami lebih awal untuk kebutuhan beberapa gelas."]], reviews: ["Kopinya konsisten enak dan baristanya paham pesanan saya.", "Cappuccino datang hangat dan foam-nya lembut.", "Matcha-nya pas, tidak terlalu manis.", "Tempat nyaman untuk kerja sebentar sore hari.", "Pesan lewat WhatsApp cepat dibalas.", "Pastry dan kopi jadi pasangan favorit saya.", "Pengantaran dekat rapi, minumannya masih segar."] },
  "demo-rumah-roti": { about: "Rumah Roti adalah bakery rumahan yang memanggang roti dalam batch kecil setiap pagi. Kami fokus pada tekstur, aroma, dan bahan yang baik untuk dinikmati hangat bersama keluarga.", highlights: [["Panggang setiap pagi", "Roti dibuat dalam batch kecil agar selalu segar.", "ChefHat"], ["Bahan pilihan", "Mentega, cokelat, dan tepung dipilih untuk rasa yang konsisten.", "Wheat"], ["Pre-order terjadwal", "Pesan lebih dulu untuk menu favorit dan kebutuhan acara kecil.", "CalendarCheck"]], faq: [["Apakah roti bisa dikirim ke luar kota?", "Untuk saat ini kami melayani pengiriman lokal agar produk tiba dalam kondisi terbaik."], ["Kapan roti dipanggang?", "Sebagian besar menu dipanggang setiap pagi."], ["Bisa pre-order?", "Bisa, terutama untuk paket sarapan dan jumlah banyak."], ["Apakah ada produk tanpa daging?", "Mayoritas pastry dan roti kami cocok sebagai pilihan tanpa daging, tanyakan detail bahan saat pesan."], ["Bagaimana menyimpan roti?", "Simpan rapat di suhu ruang dan hangatkan sebentar sebelum dinikmati."]], reviews: ["Sourdough-nya wangi dan kulitnya renyah.", "Roti sobek cokelat selalu jadi rebutan di rumah.", "Croissant almond terasa buttery dan segar.", "Pre-order paket sarapan tepat waktu.", "Donat kentangnya lembut sampai sore.", "Rasanya seperti roti rumahan yang dibuat serius.", "Admin membantu pilih menu untuk acara keluarga."] },
  "demo-nusa-craft": { about: "Nusa Craft merayakan karya tangan Nusantara dalam koleksi yang mudah dipakai sehari-hari. Setiap bahan dan detail kami pilih dengan cermat, dari tekstil tenun hingga kulit dan kanvas.", highlights: [["Karya lokal terkurasi", "Mengangkat material dan keterampilan perajin Indonesia.", "Sparkles"], ["Detail bahan jelas", "Ukuran, material, dan perawatan dijelaskan sebelum membeli.", "SearchCheck"], ["Siap jadi hadiah", "Gift set dapat disiapkan rapi untuk momen spesial.", "Gift"]], faq: [["Apakah motif tenun tiap produk sama?", "Karakter motif dapat sedikit berbeda karena proses dan potongan kain, itulah keunikan karya tekstil."], ["Bagaimana memilih ukuran pakaian?", "Hubungi kami untuk panduan ukuran dan potongan sebelum memesan."], ["Apakah tote bag cocok untuk laptop?", "Silakan tanyakan ukuran produk agar kami rekomendasikan yang sesuai kebutuhan."], ["Bisa dikirim ke luar kota?", "Bisa. Produk dikemas aman dan kami kirim melalui layanan yang tersedia."], ["Bagaimana merawat linen dan tenun?", "Cuci lembut, hindari pemutih, dan ikuti petunjuk perawatan pada produk."]], reviews: ["Kemeja linen terasa adem dan jatuhnya bagus.", "Motif outer tenunnya cantik tanpa terasa berlebihan.", "Tote bag kanvasnya kokoh untuk kerja harian.", "Scarf-nya membuat outfit sederhana jadi menarik.", "Celana rami nyaman dipakai seharian.", "Dompet kulit mini rapi dan jahitannya halus.", "Gift set-nya siap diberikan tanpa repot bungkus lagi."] },
  "demo-barber-co": { about: "Barber Co adalah ruang potong modern untuk hasil rapi yang tetap terasa personal. Kami mendengarkan gaya yang Anda inginkan sebelum barber mulai bekerja.", highlights: [["Konsultasi sebelum potong", "Barber menyesuaikan potongan dengan bentuk wajah dan rutinitas Anda.", "MessageCircle"], ["Alat higienis", "Peralatan dibersihkan dan disiapkan untuk setiap pelanggan.", "ShieldCheck"], ["Jadwal fleksibel", "Pesan slot melalui WhatsApp untuk mengurangi waktu tunggu.", "Clock"]], faq: [["Perlu reservasi?", "Reservasi disarankan, terutama pada akhir pekan."], ["Berapa lama haircut?", "Sekitar 30–45 menit, tergantung layanan dan konsultasi."], ["Bisa minta referensi gaya?", "Bisa, kirim atau tunjukkan foto referensi kepada barber."], ["Apakah layanan kids haircut tersedia?", "Tersedia dengan pendekatan yang lebih santai untuk anak."], ["Apa saja paket grooming?", "Paket dapat mencakup potong rambut, cuci, dan perapian sesuai kebutuhan."]], reviews: ["Barber-nya teliti dan hasil fade bersih.", "Potongan klasiknya rapi, mudah diatur di rumah.", "Haircut plus wash terasa praktis setelah kerja.", "Beard trim dibuat sesuai bentuk wajah saya.", "Hot towel shave-nya bikin rileks.", "Anak saya nyaman saat potong rambut di sini.", "Reservasi WhatsApp cepat dan slotnya jelas."] },
  "demo-sari-beauty": { about: "Sari Beauty menyediakan perawatan yang tenang dan terarah, dari facial sampai nail care. Terapis kami membantu memilih layanan berdasarkan kondisi dan kebutuhan Anda.", highlights: [["Konsultasi kebutuhan kulit", "Pilih perawatan berdasarkan kondisi kulit, bukan sekadar tren.", "HeartHandshake"], ["Terapis terlatih", "Setiap layanan dilakukan dengan langkah yang teliti dan nyaman.", "BadgeCheck"], ["Ruang bersih & nyaman", "Peralatan dan area perawatan disiapkan sebelum sesi dimulai.", "Sparkles"]], faq: [["Perlu konsultasi sebelum facial?", "Sangat disarankan agar kami dapat merekomendasikan perawatan yang sesuai."], ["Berapa lama sesi facial?", "Umumnya 45–75 menit, tergantung layanan."], ["Boleh datang dengan kulit sensitif?", "Boleh, informasikan kondisi kulit dan riwayat alergi saat reservasi."], ["Apakah manicure memakai alat bersih?", "Ya, peralatan disiapkan dan dibersihkan untuk setiap pelanggan."], ["Perlu reservasi?", "Reservasi WhatsApp membantu kami menyiapkan terapis dan slot yang nyaman."]], reviews: ["Facialnya lembut dan kulit terasa lebih segar.", "Terapis menjelaskan langkah perawatan dengan sabar.", "Manicure rapi dan hasilnya tahan lama.", "Gel polish warnanya cantik sesuai pilihan saya.", "Lash lift terlihat natural, tidak berlebihan.", "Hair spa-nya bikin rileks dan rambut terasa halus.", "Ruangannya bersih dan suasananya tenang."] },
  "demo-warung-sundari": { about: "Warung Sundari menyajikan masakan rumahan Nusantara dengan bumbu yang dimasak perlahan. Menu kami dibuat untuk makan hangat bersama keluarga, di tempat atau melalui pengantaran lokal.", highlights: [["Masak harian", "Menu disiapkan setiap hari untuk rasa yang hangat dan segar.", "CookingPot"], ["Bumbu rumahan", "Rendang, soto, dan ayam bakar diracik dengan bumbu Nusantara.", "Utensils"], ["Antar lokal", "Makanan siap diantar di area sekitar, bukan untuk pengiriman antarkota.", "MapPin"]], faq: [["Apakah makanan bisa dikirim ke luar kota?", "Belum. Kami menjaga rasa dan keamanan makanan dengan melayani dine-in, pick-up, dan pengantaran lokal."], ["Bisa pesan paket keluarga?", "Bisa, cocok untuk makan bersama dan dapat dipesan lebih awal."], ["Apakah bisa atur tingkat pedas?", "Bisa, tuliskan preferensi pedas saat memesan."], ["Kapan menu tersedia?", "Menu utama tersedia selama jam operasional; beberapa menu dapat habis lebih awal."], ["Bisa pesan untuk acara kecil?", "Bisa, hubungi kami untuk jumlah porsi dan waktu pengambilan."]], reviews: ["Ayam bakarnya meresap dan sambalnya mantap.", "Rendangnya kaya bumbu seperti masakan rumah.", "Soto ayamnya hangat dan segar.", "Gado-gadonya saus kacangnya pas.", "Sate ayamnya empuk dan porsinya cukup.", "Es teh manisnya segar untuk teman makan.", "Paket keluarga praktis untuk makan ramai-ramai."] },
};
const reviewNames = ["Andi Pratama", "Siti Rahma", "Rina Wijaya", "Dewi Lestari", "Bima Saputra", "Nadia Putri", "Fajar Ramadhan"];

const showcase = [
  ["demo-kopi-senja", "Kopi Senja", "Coffee Shop", "#7a4c2e", "Temukan jeda di setiap teguk.", "Kedai kopi lokal dengan suasana hangat untuk bekerja dan berbincang.", "photo-1495474472287-4d71bcdd2085", ["Es Kopi Gula Aren", "Cappuccino Klasik", "Americano", "Matcha Latte", "Croissant Butter", "Banana Bread", "Paket Kopi Pagi"], [28000, 32000, 24000, 33000, 22000, 24000, 45000], ["photo-1495474472287-4d71bcdd2085", "photo-1445116572660-236099ec97a0", "photo-1509042239860-f550ce710b93", "photo-1511081692775-05d0f180a065", "photo-1501339847302-ac426a4a7cbb", "photo-1497636577773-f1231844b336", "photo-1523942839745-7848d5c5c8e3"]],
  ["demo-rumah-roti", "Rumah Roti", "Bakery", "#a16207", "Roti hangat, dibuat setiap pagi.", "Bakery rumahan dengan roti segar, kue lembut, dan bahan pilihan.", "photo-1509440159596-0249088772ff", ["Sourdough Original", "Roti Sobek Cokelat", "Croissant Almond", "Cinnamon Roll", "Pain au Chocolat", "Donat Kentang", "Paket Sarapan"], [45000, 30000, 28000, 26000, 29000, 18000, 55000], ["photo-1509440159596-0249088772ff", "photo-1512058564366-18510be2db19", "photo-1483695028939-5bb13f8648b3", "photo-1509365465985-25d11c17e22a", "photo-1519915028121-7d3463d5b1a1", "photo-1555507036-ab1f4038808a", "photo-1549931319-a545dcf3bc73"]],
  ["demo-nusa-craft", "Nusa Craft", "Fashion", "#0f766e", "Karya lokal untuk gaya yang berkarakter.", "Koleksi fashion dan aksesori pilihan yang memadukan karya lokal dan gaya modern.", "photo-1445205170230-053b83016050", ["Kemeja Linen Aruna", "Outer Tenun Sumba", "Tote Bag Kanvas", "Scarf Motif Nusa", "Celana Santai Rami", "Dompet Kulit Mini", "Gift Set Nusantara"], [245000, 389000, 125000, 99000, 215000, 159000, 325000], ["photo-1445205170230-053b83016050", "photo-1490481651871-ab68de25d43d", "photo-1521572163474-6864f9cf17ab", "photo-1483985988355-763728e1935b", "photo-1506629905607-d405b7a30db9", "photo-1523779917675-b6ed3a42a561", "photo-1441986300917-64674bd600d8"]],
  ["demo-barber-co", "Barber Co", "Barbershop", "#1f2937", "Potongan rapi, percaya diri setiap hari.", "Barbershop modern dengan barber berpengalaman dan suasana santai.", "photo-1503951914875-452162b0f3f1", ["Classic Haircut", "Skin Fade", "Haircut + Wash", "Beard Trim", "Hot Towel Shave", "Kids Haircut", "Paket Grooming"], [50000, 65000, 75000, 35000, 55000, 40000, 115000], ["photo-1503951914875-452162b0f3f1", "photo-1622286342621-4bd786c2447c", "photo-1599351431202-1e0f0137899a", "photo-1517832207067-4db24a2ae47c", "photo-1585747860715-2ba37e788b70", "photo-1605497788044-5a32c7078486", "photo-1593702295094-aea22597af65"]],
  ["demo-sari-beauty", "Sari Beauty", "Beauty", "#db2777", "Rawat diri, pancarkan versi terbaikmu.", "Perawatan kecantikan yang personal, nyaman, dan ditangani terapis terpercaya.", "photo-1522335789203-aabd1fc54bc9", ["Basic Facial", "Brightening Facial", "Manicure Express", "Gel Polish", "Lash Lift", "Hair Spa", "Paket Glow Up"], [125000, 180000, 85000, 120000, 175000, 150000, 350000], ["photo-1522335789203-aabd1fc54bc9", "photo-1529139574466-a303027c1d8b", "photo-1512496015851-a90fb38ba796", "photo-1610992015732-2449b76344bc", "photo-1487412912498-0447578fcca8", "photo-1522337360788-8b13dee7a37e", "photo-1515377905703-c4788e51af15"]],
  ["demo-warung-sundari", "Warung Sundari", "Restaurant", "#b45309", "Rasa rumahan yang selalu dirindukan.", "Masakan Nusantara sehari-hari dengan bumbu segar dan cita rasa rumahan.", "photo-1515003197210-e0cd71810b5f", ["Nasi Ayam Bakar", "Nasi Rendang", "Soto Ayam", "Gado-Gado", "Sate Ayam", "Es Teh Manis", "Paket Keluarga"], [32000, 35000, 28000, 25000, 30000, 8000, 125000], ["photo-1515003197210-e0cd71810b5f", "photo-1565299507177-b0ac66763828", "photo-1547592180-85f173990554", "photo-1512621776951-a57141f2eefd", "photo-1529193591180-b1d58069ecdd", "photo-1556679343-c7306c1976bc", "photo-1544025162-d76694265947"]],
];

export function getShowcaseSite(slug) {
  const entry = showcase.find(([entrySlug]) => entrySlug === slug);
  if (!entry) return null;
  const [entrySlug, businessName, category, primary, heroTitle, description, cover, names, prices] = entry;
  const profile = profiles[entrySlug];
  return {
    id: `showcase-${entrySlug}`, slug: entrySlug, businessName, category, description,
    coverImageUrl: coverPhoto(entrySlug), logoUrl: logo(businessName, primary), whatsapp: "6281234567890", status: "PUBLISHED", templateStyle: "modern",
    themeConfig: { primary, accent: primary, style: "modern" },
    aiGeneratedContent: {
      heroTitle, heroSubtitle: description, heroCta: "Lihat katalog", about: profile?.about || description, productHeadline: "Pilihan favorit",
      highlights: (profile?.highlights || []).map(([title, desc, icon]) => ({ title, desc, icon })),
      faq: (profile?.faq || []).map(([q, a]) => ({ q, a })),
      testimonials: (profile?.reviews || []).map((comment, index) => ({ name: reviewNames[index], role: "Pelanggan", comment, rating: 5 })),
    },
    products: names.map((name, index) => ({ id: `${entrySlug}-${index}`, name, price: prices[index], category, images: [productPhoto(entrySlug, name)], description: `${name} pilihan ${businessName}, disiapkan dengan bahan berkualitas dan perhatian pada setiap detail.` })),
  };
}
